services:
  mongodb:
    image: mongo:7.0
    container_name: echoes-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - mongodb_config:/data/configdb
    environment:
      - MONGO_INITDB_DATABASE=${MONGO_DB_NAME}

volumes:
  mongodb_data:
  mongodb_config:
